# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 796ff39564412067632116ebd56d59e148f9d03a64f820d747f75589ecaccdebf751280ea95603803ee0e177acbebc4a690e9ff1d5f3299bdd672fea20f4d195

test:
  secret_key_base: 087ed2633c9a419655f3bc501c29ea115d07cbcc94eeecb84554de7089d190bb2cde6e1777c7182ece7f2e309746215a445f32c7a2ce8b7ca14a38669517117c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
